spring:
  datasource:
    url: ${url} # 这里的值存在heroku的环境变量中，可以通过环境变量获取
    username: ${username}
    password: ${password}
    driver-class-name: com.mysql.cj.jdbc.Driver # 数据库驱动

  jpa:
    open-in-view: false
    database: mysql
    show-sql: true # 默认false，在日志里显示执行的sql语句
    hibernate:
      ddl-auto: update # 指定为update，每次启动项目检测表结构有变化的时候会新增字段，表不存在时会新建

  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.security.servlet.UserDetailsServiceAutoConfiguration

jwt:
  # header: Authorization: Bearer XXXXXX
  expire: 43200
  # secret: 秘钥(普通字符串)
  secret: G2R0ddcHM6Ly9teS5vc2NoaW5hLm5ldC9ss1L4M2Orc32
  # 默认存放token的请求头
  requestHeader: Authorization
  # 默认token前缀
  tokenPrefix: Bearer
